Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Naming/FileName:
  Exclude:
    - lib/thor-addons.rb
    - spec/lib/thor-addons_spec.rb

# disable for now
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
