version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - run:
          name: install dependencies
          command: bundle install
      - run:
          name: Specs
          command: bundle exec rspec
